receivers:
  azuremonitor:
    subscription_id: ${env:AZURE_SUBSCRIPTION_ID}
    tenant_id: ${env:AZURE_TENANT_ID}
    client_id: ${env:AZURE_CLIENT_ID}
    client_secret: ${env:AZURE_CLIENT_SECRET}
    collection_interval: 60s
    resource_groups:
      - "rg-development-eastus"
      - "rg-production-eastus"
      - "rg-integration-eastus"
      - "rg-seed-sql-brs"
      - "rg-api-eastus"

processors:
  batch:
    timeout: 10s

exporters:
  otlp:
    endpoint: signoz-otel-collector:4317
    tls:
      insecure: true

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [azuremonitor]
      processors: [batch]
      exporters: [otlp]
